[package]
name = "pre_proc"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30.0"

polars = { version = "0.51.0", features = ["lazy", "temporal", "dtype-categorical", "csv", "parquet"] }
anyhow = "1.0"
rand = "0.8"
hashbrown = { version = "0.12", features = ["raw"] }